name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Install latest git
      run: |
        apt-get install git
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  pylint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Linting
      run: |
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  isort:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Sort Imports
      run: |
        pip install isort
    - name: Analysing the code with isort
      run: |
        isort $(git ls-files '*.py')
